# Generated by Django 5.2.1 on 2025-05-11 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='medicos/')),
                ('nome', models.CharField(max_length=100)),
                ('numero_cmr', models.CharField(max_length=50)),
                ('especialidades', models.CharField(max_length=200)),
                ('atendimento', models.TextField(help_text='Ex: Segunda a Sexta, das 08h às 18h')),
                ('diferenciais', models.TextField()),
                ('formacao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='procedimentos/')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('rotina', 'Exames de Rotina'), ('avancado', 'Exames Diagnósticos Avançados'), ('ambulatorial', 'Tratamentos e Procedimentos Ambulatoriais'), ('cirurgia', 'Cirurgias Oftalmológicas')], max_length=20)),
                ('horarios_disponiveis', models.TextField(help_text='Ex: Seg-Sex, 08h às 10h')),
                ('tempo_procedimento', models.DurationField(help_text='Ex: 00:30:00 para 30 minutos')),
                ('informacao_internacao', models.TextField()),
                ('informacao_recuperacao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicoDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.medico', verbose_name='Médico em destaque')),
            ],
            options={
                'verbose_name': 'Médico em Destaque',
                'verbose_name_plural': 'Médicos em Destaque',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('procedimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.procedimento', verbose_name='Procedimento em destaque')),
            ],
            options={
                'verbose_name': 'Procedimento em Destaque',
                'verbose_name_plural': 'Procedimentos em Destaque',
                'ordering': ['ordem'],
            },
        ),
    ]
