# Generated by Django 5.2.1 on 2025-05-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaConfirmada',
            fields=[
            ],
            options={
                'verbose_name': 'Consulta Confirmada',
                'verbose_name_plural': 'Consultas Confirmadas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.consulta',),
        ),
        migrations.AddField(
            model_name='consulta',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
