# Generated by Django 5.2.1 on 2025-05-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_consultaconfirmada_consulta_confirmada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultaconfirmada',
            options={'verbose_name': 'Consulta Confirmada', 'verbose_name_plural': 'Calendário de Agendamento'},
        ),
    ]
