# Generated by Django 5.2.3 on 2025-06-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_consultaconfirmada_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='procedimentos',
            field=models.ManyToManyField(blank=True, related_name='medicos', to='app.procedimento'),
        ),
    ]
