# Generated by Django 5.2.1 on 2025-06-29 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_medico_procedimentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira')], max_length=10)),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='app.procedimento')),
            ],
            options={
                'ordering': ['procedimento', 'dia', 'turno', 'hora_inicio'],
                'unique_together': {('procedimento', 'dia', 'turno', 'hora_inicio', 'hora_fim')},
            },
        ),
    ]
