# Generated by Django 5.2.1 on 2025-06-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_horarioprocedimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='horarios_disponiveis',
        ),
    ]
