# Generated by Django 5.2.1 on 2025-06-29 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_procedimento_horarios_disponiveis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14)),
                ('dia', models.CharField(choices=[('segunda', 'Segunda'), ('terca', 'Terça'), ('quarta', 'Quarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta')], max_length=10)),
                ('tipo_procedimento', models.CharField(max_length=50)),
                ('procedim', models.CharField(blank=True, max_length=50, null=True)),
                ('turno', models.CharField(max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('data_atribuida', models.DateField(blank=True, null=True)),
                ('confirmada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medico')),
            ],
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='medico',
        ),
        migrations.DeleteModel(
            name='ConsultaConfirmada',
        ),
        migrations.CreateModel(
            name='AgendaConfirmada',
            fields=[
            ],
            options={
                'verbose_name': 'Agenda Confirmada',
                'verbose_name_plural': 'Calendário de Agendamento',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.agenda',),
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
