# Generated by Django 5.2.1 on 2025-06-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_agenda_remove_consulta_medico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='procedim',
            new_name='procedimento',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='tipo_procedimento',
            new_name='tipo',
        ),
    ]
